### ISSUE TITLE
TypingError: got an unexpected keyword argument 'ddof' using jit_filter_function on Windows

### ISSUE THREAD

**Issue by jbrown-maxar** [jni/llc-tools#14]
Hello!  First I'd like to say this decorator has been great to work with, really appreciate jit_filter_function.  I'm running into an error that pops up when adding the 'ddof' argument to np.nanstd within the filter function.

This code runs without flaw
```
@jit_filter_function
def fstd(values):
    values[values == 0] = np.nan
    result = np.nanstd(values)
    return result
std = generic_filter(<2d_numpy_array>, fstd, footprint=np.ones((5, 5)))
```

However, adding the ddof argument like this
```
@jit_filter_function
def fstd(values):
    values[values == 0] = np.nan
    result = np.nanstd(values, ddof=1)
    return result
std = generic_filter(<2d_numpy_array>, fstd, footprint=np.ones((5, 5)))
```
Throws this:
```
Traceback (most recent call last):
  File "C:/Users/jbrown/AppData/Roaming/JetBrains/PyCharmCE2021.1/scratches/hr_class_master.py", line 301, in <module>
    main()
  File "C:\Users\jbrown\AppData\Local\Programs\Python\Python38\lib\site-packages\memory_profiler.py", line 1186, in wrapper
    val = prof(func)(*args, **kwargs)
  File "C:\Users\jbrown\AppData\Local\Programs\Python\Python38\lib\site-packages\memory_profiler.py", line 759, in f
    return func(*args, **kwds)
  File "C:/Users/jbrown/AppData/Roaming/JetBrains/PyCharmCE2021.1/scratches/hr_class_master.py", line 149, in main
    def fstd(values):
  File "C:\Users\jbrown\AppData\Local\Programs\Python\Python38\lib\site-packages\llc\ndimage.py", line 48, in jit_filter_function
    def wrapped(values_ptr, len_values, result, data):
  File "C:\Users\jbrown\AppData\Local\Programs\Python\Python38\lib\site-packages\numba\core\decorators.py", line 282, in wrapper
    res.compile()
  File "C:\Users\jbrown\AppData\Local\Programs\Python\Python38\lib\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\jbrown\AppData\Local\Programs\Python\Python38\lib\site-packages\numba\core\ccallback.py", line 67, in compile
    cres = self._compile_uncached()
  File "C:\Users\jbrown\AppData\Local\Programs\Python\Python38\lib\site-packages\numba\core\ccallback.py", line 81, in _compile_uncached
    return self._compiler.compile(sig.args, sig.return_type)
  File "C:\Users\jbrown\AppData\Local\Programs\Python\Python38\lib\site-packages\numba\core\dispatcher.py", line 129, in compile
    raise retval
  File "C:\Users\jbrown\AppData\Local\Programs\Python\Python38\lib\site-packages\numba\core\dispatcher.py", line 139, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "C:\Users\jbrown\AppData\Local\Programs\Python\Python38\lib\site-packages\numba\core\dispatcher.py", line 152, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "C:\Users\jbrown\AppData\Local\Programs\Python\Python38\lib\site-packages\numba\core\compiler.py", line 716, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Users\jbrown\AppData\Local\Programs\Python\Python38\lib\site-packages\numba\core\compiler.py", line 452, in compile_extra
    return self._compile_bytecode()
  File "C:\Users\jbrown\AppData\Local\Programs\Python\Python38\lib\site-packages\numba\core\compiler.py", line 520, in _compile_bytecode
    return self._compile_core()
  File "C:\Users\jbrown\AppData\Local\Programs\Python\Python38\lib\site-packages\numba\core\compiler.py", line 499, in _compile_core
    raise e
  File "C:\Users\jbrown\AppData\Local\Programs\Python\Python38\lib\site-packages\numba\core\compiler.py", line 486, in _compile_core
    pm.run(self.state)
  File "C:\Users\jbrown\AppData\Local\Programs\Python\Python38\lib\site-packages\numba\core\compiler_machinery.py", line 368, in run
    raise patched_exception
  File "C:\Users\jbrown\AppData\Local\Programs\Python\Python38\lib\site-packages\numba\core\compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "C:\Users\jbrown\AppData\Local\Programs\Python\Python38\lib\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\jbrown\AppData\Local\Programs\Python\Python38\lib\site-packages\numba\core\compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "C:\Users\jbrown\AppData\Local\Programs\Python\Python38\lib\site-packages\numba\core\compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
  File "C:\Users\jbrown\AppData\Local\Programs\Python\Python38\lib\site-packages\numba\core\typed_passes.py", line 105, in run_pass
    typemap, return_type, calltypes, errs = type_inference_stage(
  File "C:\Users\jbrown\AppData\Local\Programs\Python\Python38\lib\site-packages\numba\core\typed_passes.py", line 83, in type_inference_stage
    errs = infer.propagate(raise_errors=raise_errors)
  File "C:\Users\jbrown\AppData\Local\Programs\Python\Python38\lib\site-packages\numba\core\typeinfer.py", line 1086, in propagate
    raise errors[0]
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<function nanstd at 0x000001BA5B414F70>) found for signature:
 
 >>> nanstd(array(float64, 1d, C), ddof=Literal[int](1))
 
There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'np_nanstd': File: numba\np\arraymath.py: Line 1231.
    With argument(s): '(array(float64, 1d, C), ddof=int64)':
   Rejected as the implementation raised a specific error:
     TypingError: got an unexpected keyword argument 'ddof'
  raised from C:\Users\jbrown\AppData\Local\Programs\Python\Python38\lib\site-packages\numba\core\typing\templates.py:791

During: resolving callee type: Function(<function nanstd at 0x000001BA5B414F70>)
During: typing of call at C:/Users/jbrown/AppData/Roaming/JetBrains/PyCharmCE2021.1/scratches/hr_class_master.py (151)


File "hr_class_master.py", line 151:
    def fstd(values):
        <source elided>
        values[values == 0] = np.nan
        result = np.nanstd(values, ddof=1)
        ^

During: resolving callee type: type(CPUDispatcher(<function main.<locals>.fstd at 0x000001BA0DBF04C0>))
During: typing of call at C:\Users\jbrown\AppData\Local\Programs\Python\Python38\lib\site-packages\llc\ndimage.py (50)

During: resolving callee type: type(CPUDispatcher(<function main.<locals>.fstd at 0x000001BA0DBF04C0>))
During: typing of call at C:\Users\jbrown\AppData\Local\Programs\Python\Python38\lib\site-packages\llc\ndimage.py (50)


File "..\..\..\..\Local\Programs\Python\Python38\lib\site-packages\llc\ndimage.py", line 50:
    def wrapped(values_ptr, len_values, result, data):
        <source elided>
        values = carray(values_ptr, (len_values,), dtype=float64)
        result[0] = jitted_function(values)
        ^
```

Is this functionality to be added, or error with the code itself?  I'm using **Python 3.8 on Windows**

**Comment by jni** [comment]
Hey! Glad to hear it is useful! 😊 (Still — I haven't revisited this package anywhere near as much as I'd like to.)

Anyway, it seems you've hit a numba issue. Numba has support for many NumPy functions inside JITted functions, but if you look closely at this part of the error:

```pytb
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<function nanstd at 0x000001BA5B414F70>) found for signature:
 
 >>> nanstd(array(float64, 1d, C), ddof=Literal[int](1))
 
There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'np_nanstd': File: numba\np\arraymath.py: Line 1231.
    With argument(s): '(array(float64, 1d, C), ddof=int64)':
   Rejected as the implementation raised a specific error:
     TypingError: got an unexpected keyword argument 'ddof'
  raised from C:\Users\jbrown\AppData\Local\Programs\Python\Python38\lib\site-packages\numba\core\typing\templates.py:791
```

it's not expecting the ddof argument, and if you look at their NumPy support page:

https://numba.readthedocs.io/en/stable/reference/numpysupported.html#reductions

indeed it says that only the first argument of nanstd is supported.

You could raise an issue with numba, or you can code up your own nanstd (or nnzstd since you're apparently just looking to get rid of zeros?) and jit-compile it with Numba. Something like:

```python
@numba.njit
def nnzstd(arr):
    nz = arr[arr != 0]
    n = len(nz)
    if n <= 1:
        return np.nan
    mu = np.mean(nz)
    var = np.sum((nz - mu) ** 2) / n - 1
    std = np.sqrt(var)
    return std
```

Since this is not an llc issue I'm going to close it, but please feel free to continue discussing this issue here if you have more questions!
