### ISSUE TITLE
Sample code on your blog not working

### ISSUE THREAD

**Issue by AlvarHHM** [jni/llc-tools#2]
I followed your code on https://ilovesymposia.com/2017/03/15/prettier-lowlevelcallables-with-numba-jit-and-decorators/
```
import numba
from numba import cfunc, carray, jit
from numba.types import intc, CPointer, float64, intp, voidptr, uint8
from scipy import LowLevelCallable

def jit_filter_function(filter_function):
    """Decorator for use with scipy.ndimage.generic_filter."""
    jitted_function = numba.jit(filter_function, nopython=True)

    @cfunc(intc(CPointer(float64), intp, CPointer(float64), voidptr))
    def wrapped(values_ptr, len_values, result, data):
        values = carray(values_ptr, (len_values,), dtype=float64)
        result[0] = jitted_function(values)
        return 1
    return LowLevelCallable(wrapped.ctypes)

@jit_filter_function
def fmin(values):
    result = np.inf
    for v in values:
        if v < result:
            result = v
```

Encountered the following error
```
LoweringError: Caused By:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/numba/compiler.py", line 238, in run
    stage()
  File "/usr/local/lib/python2.7/site-packages/numba/compiler.py", line 644, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "/usr/local/lib/python2.7/site-packages/numba/compiler.py", line 599, in _backend
    lowered = lowerfn()
  File "/usr/local/lib/python2.7/site-packages/numba/compiler.py", line 586, in backend_nopython_mode
    self.flags)
  File "/usr/local/lib/python2.7/site-packages/numba/compiler.py", line 882, in native_lowering_stage
    lower.lower()
  File "/usr/local/lib/python2.7/site-packages/numba/lowering.py", line 135, in lower
    self.lower_normal_function(self.fndesc)
  File "/usr/local/lib/python2.7/site-packages/numba/lowering.py", line 176, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/usr/local/lib/python2.7/site-packages/numba/lowering.py", line 201, in lower_function_body
    self.lower_block(block)
  File "/usr/local/lib/python2.7/site-packages/numba/lowering.py", line 216, in lower_block
    self.lower_inst(inst)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/site-packages/numba/errors.py", line 265, in new_error_context
    six.reraise(type(newerr), newerr, sys.exc_info()[2])
  File "/usr/local/lib/python2.7/site-packages/numba/errors.py", line 259, in new_error_context
    yield
  File "/usr/local/lib/python2.7/site-packages/numba/lowering.py", line 216, in lower_block
    self.lower_inst(inst)
  File "/usr/local/lib/python2.7/site-packages/numba/lowering.py", line 305, in lower_inst
    return self.lower_setitem(inst.target, inst.index_var, inst.value, signature)
  File "/usr/local/lib/python2.7/site-packages/numba/lowering.py", line 390, in lower_setitem
    signature.args[2])
  File "/usr/local/lib/python2.7/site-packages/numba/targets/base.py", line 648, in cast
    "Cannot cast %s to %s: %s" % (fromty, toty, val))
LoweringError: Cannot cast none to float64: %".117" = load i8*, i8** %"$0.10"
File "<ipython-input-52-1ddc111374d6>", line 13
[1] During: lowering "result[0] = $0.10" at <ipython-input-52-1ddc111374d6> (13)

Failed at nopython (nopython mode backend)
Cannot cast none to float64: %".117" = load i8*, i8** %"$0.10"
File "<ipython-input-52-1ddc111374d6>", line 13
[1] During: lowering "result[0] = $0.10" at <ipython-input-52-1ddc111374d6> (13)
LoweringErrorTraceback (most recent call last)
<ipython-input-52-1ddc111374d6> in <module>()
     15     return LowLevelCallable(wrapped.ctypes)
     16 
---> 17 @jit_filter_function
     18 def fmin(values):
     19     result = np.inf
<ipython-input-52-1ddc111374d6> in jit_filter_function(filter_function)
      8     jitted_function = numba.jit(filter_function, nopython=True)
      9 
---> 10     @cfunc(intc(CPointer(float64), intp, CPointer(float64), voidptr))
     11     def wrapped(values_ptr, len_values, result, data):
     12         values = carray(values_ptr, (len_values,), dtype=float64)
/usr/local/lib/python2.7/site-packages/numba/decorators.pyc in wrapper(func)
    251         if cache:
    252             res.enable_caching()
--> 253         res.compile()
    254         return res
    255 
/usr/local/lib/python2.7/site-packages/numba/ccallback.pyc in compile(self)
     65             cres = self._cache.load_overload(self._sig, self._targetdescr.target_context)
     66             if cres is None:
---> 67                 cres = self._compile_uncached()
     68                 self._cache.save_overload(self._sig, cres)
     69             else:
/usr/local/lib/python2.7/site-packages/numba/ccallback.pyc in _compile_uncached(self)
     78 
     79         # Compile native function
---> 80         cres = self._compiler.compile(sig.args, sig.return_type)
     81         assert not cres.objectmode  # disabled by compiler above
     82         fndesc = cres.fndesc
/usr/local/lib/python2.7/site-packages/numba/dispatcher.pyc in compile(self, args, return_type)
     78                                       impl,
     79                                       args=args, return_type=return_type,
---> 80                                       flags=flags, locals=self.locals)
     81         # Check typing error if object mode is used
     82         if cres.typing_error is not None and not flags.enable_pyobject:
/usr/local/lib/python2.7/site-packages/numba/compiler.pyc in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library)
    761     pipeline = Pipeline(typingctx, targetctx, library,
    762                         args, return_type, flags, locals)
--> 763     return pipeline.compile_extra(func)
    764 
    765 
/usr/local/lib/python2.7/site-packages/numba/compiler.pyc in compile_extra(self, func)
    358         self.lifted = ()
    359         self.lifted_from = None
--> 360         return self._compile_bytecode()
    361 
    362     def compile_ir(self, func_ir, lifted=(), lifted_from=None):
/usr/local/lib/python2.7/site-packages/numba/compiler.pyc in _compile_bytecode(self)
    720         """
    721         assert self.func_ir is None
--> 722         return self._compile_core()
    723 
    724     def _compile_ir(self):
/usr/local/lib/python2.7/site-packages/numba/compiler.pyc in _compile_core(self)
    707 
    708         pm.finalize()
--> 709         res = pm.run(self.status)
    710         if res is not None:
    711             # Early pipeline completion
/usr/local/lib/python2.7/site-packages/numba/compiler.pyc in run(self, status)
    244                     # No more fallback pipelines?
    245                     if is_final_pipeline:
--> 246                         raise patched_exception
    247                     # Go to next fallback pipeline
    248                     else:
LoweringError: Caused By:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/numba/compiler.py", line 238, in run
    stage()
  File "/usr/local/lib/python2.7/site-packages/numba/compiler.py", line 644, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "/usr/local/lib/python2.7/site-packages/numba/compiler.py", line 599, in _backend
    lowered = lowerfn()
  File "/usr/local/lib/python2.7/site-packages/numba/compiler.py", line 586, in backend_nopython_mode
    self.flags)
  File "/usr/local/lib/python2.7/site-packages/numba/compiler.py", line 882, in native_lowering_stage
    lower.lower()
  File "/usr/local/lib/python2.7/site-packages/numba/lowering.py", line 135, in lower
    self.lower_normal_function(self.fndesc)
  File "/usr/local/lib/python2.7/site-packages/numba/lowering.py", line 176, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/usr/local/lib/python2.7/site-packages/numba/lowering.py", line 201, in lower_function_body
    self.lower_block(block)
  File "/usr/local/lib/python2.7/site-packages/numba/lowering.py", line 216, in lower_block
    self.lower_inst(inst)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/site-packages/numba/errors.py", line 265, in new_error_context
    six.reraise(type(newerr), newerr, sys.exc_info()[2])
  File "/usr/local/lib/python2.7/site-packages/numba/errors.py", line 259, in new_error_context
    yield
  File "/usr/local/lib/python2.7/site-packages/numba/lowering.py", line 216, in lower_block
    self.lower_inst(inst)
  File "/usr/local/lib/python2.7/site-packages/numba/lowering.py", line 305, in lower_inst
    return self.lower_setitem(inst.target, inst.index_var, inst.value, signature)
  File "/usr/local/lib/python2.7/site-packages/numba/lowering.py", line 390, in lower_setitem
    signature.args[2])
  File "/usr/local/lib/python2.7/site-packages/numba/targets/base.py", line 648, in cast
    "Cannot cast %s to %s: %s" % (fromty, toty, val))
LoweringError: Cannot cast none to float64: %".117" = load i8*, i8** %"$0.10"
File "<ipython-input-52-1ddc111374d6>", line 13
[1] During: lowering "result[0] = $0.10" at <ipython-input-52-1ddc111374d6> (13)

Failed at nopython (nopython mode backend)
Cannot cast none to float64: %".117" = load i8*, i8** %"$0.10"
File "<ipython-input-52-1ddc111374d6>", line 13
[1] During: lowering "result[0] = $0.10" at <ipython-input-52-1ddc111374d6> (13)
```

**Comment by jni** [comment]
@AlvarHHM You forgot "return result" at the end! =)

**Comment by AlvarHHM** [comment]
OMG, silly me, thank you....
